# Run the entire application from pre-built, saved images.
services:
  web:
    image: ${FINAL_API_IMAGE}
    command: rerun --background 'ruby app.rb'
    volumes:
      - .:/app
    ports:
      - "${WEB_PORT:-1500}:1500"
    depends_on:
      - redis
    environment:
      - REDIS_ENABLED=true
      - REDIS_URL=redis://redis:6379
  redis:
    image: redis:5.0.8
    ports:
      - "${REDIS_PORT:-6379}:6379"
  cache:
    image: nginx:1.17.9
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./tmp/nginx:/var/cache/nginx
    ports:
      - "${NGINX_PORT:-1501}:1501"
    depends_on:
      - web